version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install grpcio grpcio-tools
      - pip install boto3
  pre_build:
    commands:
      - echo "Preparing to deploy"
  build:
    commands:
      - echo "Building Docker image"
      - docker build -t <DOCKER_IMAGE> .
      - echo "Pushing Docker image to ECR"
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker push <DOCKER_IMAGE>
  post_build:
    commands:
      - echo "Deployment finished"
